export const FETCH_PRODUCTS_PENDING = 'FETCH_PRODUCTS_PENDING'
export const FETCH_PRODUCTS_SUCCESS = 'FETCH_PRODUCTS_SUCCESS' 
export const FETCH_PRODUCTS_FAILED = 'FETCH_PRODUCTS_FAILED'

export const SIGNIN_EMAIL = 'SIGNIN_EMAIL'
export const SIGNIN_PASSWORD = 'SIGNIN_PASSWORD' 
export const SIGNIN_ERR = 'SIGNIN_ERR'

export const FETCH_USER_DETAILS = 'FETCH_USER_DETAILS'
export const FETCH_CART_DETAILS = 'FETCH_CART_DETAILS'
export const RESPONSE_LOADER = 'RESPONSE_LOADER'
